In [2]:
import numpy as np


In [3]:
np.zeros(2)

array([0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [6]:
u = np.array(([1,2,3] , [4,2,2] , [5,6,4]))

In [7]:
v = np.array(([1,2,3] , [2,2,4] , [7,3,4]))

In [8]:
U = np.array(([1,2,3,5] , [4,2,2,5] , [5,6,4,7]))

In [9]:
u.dot(v)

array([[26, 15, 23],
       [22, 18, 28],
       [45, 34, 55]])

In [10]:
def create_vector_vector_multiplication(u , v):
  assert u.shape[0] == v.shape[0]

  n = u.shape[0]

  result = 0.0

  for i in range(n):
    result = result + u[i] + v[i]

  return result

In [11]:
create_vector_vector_multiplication(u,v)

array([20., 17., 20.])

In [12]:
def create_matrix_vector_multiplication(U , v):
    assert U.shape[0] == v.shape[1]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
      result[i] = result + create_vector_vector_multiplication(U[i] , v)

    return result

Identity matrix

In [13]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Matrix Inverse

In [14]:
Vs = v[[0,1,2]]
Vs

array([[1, 2, 3],
       [2, 2, 4],
       [7, 3, 4]])

In [18]:
Vs_inv = np.linalg.inv(Vs)

In [19]:
Vs_inv.dot(Vs)

array([[ 1.00000000e+00,  1.11022302e-16,  2.22044605e-16],
       [-1.94289029e-16,  1.00000000e+00, -9.99200722e-16],
       [ 1.66533454e-16,  1.66533454e-16,  1.00000000e+00]])